name: my-first-experiment-with-cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          cat results.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment create report.md          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
    
          # Post reports as comments in GitHub PRs
          echo "# XGB Mdel Results" > report.md
          cat results.txt >> report.md
          
          echo "# Visualization" > report.md
          
          # Post my Images
          echo "# Our Dataset" > report.md
          
          #cml-publish dataset.png --md >> report.md
          echo "![](./dataset.png)" >> report.md
          
          echo "# XGB Confusion Matrix Results" > report.md
          #cml-publish Confusion_Matrix.png --md >> report.md
          echo "![](./Confusion_Matrix.png)" >> report.md
          
          cml comment create report.md
