name: my-first-experiment-with-cml
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          #cat results.txt >> report.md
          echo 1 > report.md
          # Post reports as comments in GitHub PRs
          #echo "XGB Mdel Results" > report.md
          #cat results.txt >> report.md
          
          #echo "# Visualization" > report.md
          
          # Post my Images
          #echo "# Our Dataset" > report.md
          
          #echo "![](./dataset.png)" >> report.md
          
          #echo "# XGB Confusion Matrix Results" > report.md
          #echo "![](./Confusion_Matrix.png)" >> report.md
          
          cml comment create report.md
